name: server
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build to docker container
        uses: docker/setup-buildx-action@v1
      - run: npm install --global yarn
      - run: yarn
      - run: yarn run build
      - run: docker build . -t bare-metal-automation/bare-metal-automation
        env:
          CI: true